# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
- master+static-0920+pdftopngs

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      rm -rf build
      mkdir build
      cd build

      cmake -G "MSYS Makefiles" \
        -D CMAKE_INSTALL_PREFIX=~/poppler-release \
        -D CMAKE_BUILD_TYPE=Release \
        -D BUILD_CPP_TESTS:BOOL=OFF \
        -D ENABLE_QT5:BOOL=OFF \
        -D ENABLE_GLIB:BOOL=OFF \
        -D ENABLE_ZLIB_UNCOMPRESS:BOOL=ON \
        -DFREETYPE_LIBRARY=/mingw32/lib/libfreetype.a \
        -DFREETYPE_INCLUDE_DIRS=/mingw32/include/freetype2 \
        ..
      make
