# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

# HKEY_USERS\S-1-5-20\Environment!Path
# - `%USERPROFILE%\AppData\Local\Microsoft\WindowsApps;C:\msys32`

trigger:
- dev-ng

pool:
 demands:
 - POPPLER_WIN32_BUILDER -equals 1

steps:
- task: DeleteFiles@1
  inputs:
    SourceFolder: '$(Build.BinariesDirectory)'
    Contents: 'poppler-release'

- task: CmdLine@2
  displayName: Build poppler
  env:
    BinariesDirectory: $(Build.BinariesDirectory)
    SourcesDirectory: $(Build.SourcesDirectory)
  inputs:
    script: |
      call msys2_shell.cmd -mingw32 -defterm -here -no-start build.sh x86
      call msys2_shell.cmd -mingw64 -defterm -here -no-start build.sh x64 || true

- task: DotNetCoreCLI@2
  env:
    BinariesDirectory: $(Build.BinariesDirectory)
    SourcesDirectory: $(Build.SourcesDirectory)
  inputs:
    command: 'test'
    projects: |
      **/tester.csproj
    arguments: ''

- task: CopyFiles@2
  displayName: Copy poppler
  inputs:
    SourceFolder: '$(Build.BinariesDirectory)\poppler-release'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'win32-static-release'
    publishLocation: 'Container'
